name: automarge2
on:
  push:
    branches:
      - '*'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge DEV1 -> main
        uses: cesarh84/merge-branch@main
        with:
          type: now
          from_branch: DEV1
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}

      
