name: automerge2
on:
  push:
    branches:
      - 'release/*'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Merge TEST_QA -> main
        uses: cesarh84/TEST_QA@main
        with:
          type: now
          target_branch: main
          message: Merge TEST_GA into main
          github_token: ${{ secrets.GITHUB_TOKEN }}
