name: automerge2
on:
  pull_request:
    types: [labeled]
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Merge by labeled
        uses: cesarh84/merge-branch@main
        with:
          label_name: 'merged in develop'
          target_branch: 'DEV1'
          github_token: ${{ secrets.GITHUB_TOKEN }}
